# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: On push of a tag
on:
  push:
    tags:
    - v*

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: bootc-on-ox

jobs:
  buildrelease:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Parse version
      id: parse_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
    
    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.redhat.io

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "${{ env.IMAGE }}"
        tags: latest prod ${{ steps.parse_version.outputs.VERSION }} ${{ github.sha }}
        platforms: linux/arm64
        containerfiles: |
          ./bootc/Containerfile
  
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0
    
    - name: Get image sha
      id: imagesha
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE }}
        tags: latest prod ${{ steps.parse_version.outputs.VERSION }} ${{ github.sha }} 
        registry: quay.io/${{ env.REGISTRY_USER }}

    - name: Sign image
      run: cosign sign  --yes -a sha=${{ github.sha }} -a run_id=${{github.run_id}} -a run_attempt="$GITHUB_RUN_ATTEMPT" quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}:`podman image inspect --format '{{ .Digest }}' quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}`